### ISSUE TITLE
Bug; New asp.net core 3.1 project; Builtin Sergen throws error on tables with 1:n relation; MySQL 8.0 RDBMS

### ISSUE THREAD

**Issue by JohnRanger** [serenity-is/Serenity#5259]
Hi @volkanceylan , @VictorTomaili ,

I am starting a fresh project from newest Serene template - but this time for the 1st time with a MySQL backend (MySQL 8.0.22).

So far, the basic Serene project works fine - but I encounter consistently an error with the Web-builtin Sergen, when trying to produce code on tables which are the "n" side of an 1:n relation with another table.

Producing code for tables which are the "1" side of a 1:n relation works fine.

Here an excerpt from such relations - the orange table throw the Sergen error, the green ones do work (I have tried some more of the "n" side tables - and they all throw the same error with sergen).

![image](https://user-images.githubusercontent.com/2699447/97082729-27ea0980-160c-11eb-928c-c50aad66cf7b.png)

The error message of the Web-Sergen does not say anything which could be used for further troubleshooting:

![image](https://user-images.githubusercontent.com/2699447/97080137-92457e80-15f9-11eb-83be-d30f16828295.png)

-----------------

The same happens with the dotnet sergen commandline version (orange tables crash sergen, green one works). But here comes a clear crash exception message:

-------------

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Serenity.CodeGenerator.RowGenerator.<>c__DisplayClass5_3.<GenerateModel>b__12(ForeignKeyInfo k) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\Generator\RowGenerator.cs:line 264
   at System.Collections.Generic.List`1.Find(Predicate`1 match)
   at Serenity.CodeGenerator.RowGenerator.GenerateModel(IDbConnection connection, String tableSchema, String table, String module, String connectionKey, String entityClass, String permission, GeneratorConfig config) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\Generator\RowGenerator.cs:line 264
   at Serenity.CodeGenerator.GenerateCommand.Run(String csproj, String[] args) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\Commands\GenerateCommand.cs:line 388
   at Serenity.CodeGenerator.Program.Main(String[] args) in C:\Sandbox\StartSharp\Serenity\Serenity.CodeGenerator\Program.cs:line 104

--------------------

**Edit:** When I just remove the relationship between the table which throws the error and the ones which do work - then sergen has no problems to create the code (but of course that makes no fun without the xyzRow.cs having any of the foreign fields).

--------------------

May I kindly ask you to have a look into this?

With kind regards,

John

**Comment by JohnRanger** [comment]
It looks that I have had the relationship in the wrong direction. Within MySQL workbench, you have to draw the Relationship from the N-side to the 1-side (this is contrary to what intuition and MSSQL Management Studio is doing it).
