### ISSUE TITLE
[Bug report]: "The file is not a valid VSIX package" when trying to install the serene extension

### ISSUE THREAD

**Issue by ali-h2010** [serenity-is/Serenity#6772]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

I am not able to install the Serenity Template Extension from Visual Studio Market Place.

Installer is showing that "The file is not a valid VSIX package"
I have tested installing other extensions and they are working fine.

### What did you expect to happen?

To install Serene Extension on Visual Studio 2022 Community edition.

System Details:
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.5.5

### How to reproduce?

1- install visual studio 2022 and make sure it's updated to latest version
2- Access the market place and download the serene extension
https://marketplace.visualstudio.com/items?itemName=VolkanCeylan.SereneSerenityApplicationTemplate
3- double click on the downloaded item to install it.
4- getting the error "

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

N/A

### Relevant log output

```console
Full Error Log

5/11/2023 11:14:03 AM - Microsoft VSIX Installer
5/11/2023 11:14:03 AM - -------------------------------------------
5/11/2023 11:14:03 AM - vsixinstaller.exe version:
5/11/2023 11:14:03 AM - 17.5.4074+g1de9468fa7
5/11/2023 11:14:03 AM - -------------------------------------------
5/11/2023 11:14:03 AM - Command line parameters:
5/11/2023 11:14:03 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\ahalkhamis\Downloads\Serene.Template (1).vsix
5/11/2023 11:14:03 AM - -------------------------------------------
5/11/2023 11:14:03 AM - Microsoft VSIX Installer
5/11/2023 11:14:03 AM - -------------------------------------------
5/11/2023 11:14:04 AM - Initializing Install...
5/11/2023 11:14:04 AM - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package. ---> System.IO.FileFormatException: Archive file cannot be size 0.
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```
```


### Serene template version

_No response_

### Sergen version

_No response_

### Code editor

_No response_

### Operating System

_No response_

### Node.js version

_No response_

### TypeScript version

_No response_

### Database type and version

_No response_

### On which device do you see the problem?

_No response_

### On which operating system do you see the problem?

_No response_

### On which browsers do you see the problem?

_No response_

### On what version of the browsers do you see the problem?

_No response_

### Additional information

_No response_

**Comment by VictorTomaili** [comment]
`The file is not a valid VSIX package. ---> System.IO.FileFormatException: Archive file cannot be size 0.` means while you are downloading the vsix package, some network issue occurred. The vsix file size is zero. I downloaded and installed from your link, and it is working as expected. 

Verify your download from below checksum. You can use 7zip > CRC SHA > SHA-256 option.

```
Name: Serene.Template.vsix
Size: 3041807 bytes (2970 KiB)
SHA256: 29e95d0a72c2878e31a182c6b73e7233899a0c976ebdacc6e8c0ef844e1122f4
```
