### ISSUE TITLE
[Bug report]: Sergen g Not work with oracle

### ISSUE THREAD

**Issue by hamadaDev** [serenity-is/Serenity#6833]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

try genrate oracle tabels by 
dotnet sergen g

### What did you expect to happen?

can genrate the tabels or show tabels names in the list 
and I'm RegisterDataProviders Oracle.ManagedDataAccess.Client
![image](https://github.com/serenity-is/Serenity/assets/11373077/de22158c-6c73-4450-9073-a5ee9932e93a)

### How to reproduce?

need to make sergen g can work  with oracle database 

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

6.7.1.0

### Relevant log output

```console
dotnet sergen g

── Table Code Generation ─────────────────────────────────────────────────────────────────────────────
System.ArgumentException: The specified invariant name 'Oracle.ManagedDataAccess.Client' wasn't found in the list of registered .NET Data Providers.
   at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName, Boolean throwOnError)
   at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at Serenity.Data.DefaultSqlConnections.CreateConnection(String connectionString, String providerName, ISqlDialect dialect) in C:\Sandbox\startsharp\Serenity\src\Serenity.Net.Data\Connections\DefaultSqlConnections.cs:line 55
   at Serenity.Data.DefaultSqlConnections.New(String connectionString, String providerName, ISqlDialect dialect) in C:\Sandbox\startsharp\Serenity\src\Serenity.Net.Data\Connections\DefaultSqlConnections.cs:line 93
   at Serenity.Data.DefaultSqlConnections.NewByKey(String connectionKey) in C:\Sandbox\startsharp\Serenity\src\Serenity.Net.Data\Connections\DefaultSqlConnections.cs:line 108
   at Serenity.CodeGenerator.GenerateCommand.Interactive.SelectedTables(ISqlConnections sqlConnections, String connectionKey) in C:\Sandbox\startsharp\Serenity\src\Serenity.Net.CodeGenerator\Commands\GenerateCommand.Interactive.cs:line 185
   at Serenity.CodeGenerator.GenerateCommand.Interactive.Run() in C:\Sandbox\startsharp\Serenity\src\Serenity.Net.CodeGenerator\Commands\GenerateCommand.Interactive.cs:line 45
   at Serenity.CodeGenerator.GenerateCommand.Run(String csproj, String[] args) in C:\Sandbox\startsharp\Serenity\src\Serenity.Net.CodeGenerator\Commands\GenerateCommand.cs:line 55
   at Serenity.CodeGenerator.Program.Run(String[] args, IGeneratorFileSystem fileSystem, Func`1 projectSystemFactory) in C:\Sandbox\startsharp\Serenity\src\Serenity.Net.CodeGenerator\Program.cs:line 156
==============
"C:\Sandbox\startsharp\ " this path not in my pc maybe this from development pc
==============
```

### Sergen version

6.7.1.0

### Code editor

vs 2022

### Operating System

windows 10

### Node.js version

16.18.1

### Database type and version

Oracle 12

### On which browsers do you see the problem?

Chrome

**Comment by hamadaDev** [comment]
DefaultSqlConnections.cs  : Line 55 
var factory = DbProviderFactories.GetFactory(providerName);
I'm try to  read the code may  be find some thing help

**Comment by VictorTomaili** [comment]
`dotnet sergen` is a standalone application, whereas the oracle provider is not supported currently. 
You can create modules manually instead.
