### ISSUE TITLE
[Bug report]: Run on IIS Error, help me

### ISSUE THREAD

**Issue by CitysoftInfotech** [serenity-is/Serenity#6855]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

An error occurred while starting the application.
ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
string.Substring(int startIndex, int length)

ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
string.Substring(int startIndex, int length)
Serenity.Extensions.DependencyInjection.ServiceCollectionExtensions.AddJsonTexts(ILocalTextRegistry registry, IFileProvider provider, string subpath, bool recursive) in ServiceCollectionExtensions.cs
Serenity.Extensions.DependencyInjection.ServiceCollectionExtensions.AddBaseTexts(IServiceProvider provider, IFileProvider webFileProvider) in ServiceCollectionExtensions.cs
Fascino.Startup.InitializeLocalTexts(IServiceProvider services) in Startup.cs
Fascino.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in Startup.cs
System.RuntimeMethodHandle.InvokeMethod(object target, ref Span<object> arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.ConfigureBuilder+<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder+<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
StackExchange.Exceptional.ExceptionalStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
Fascino.Program.Main(string[] args) in Program.cs

Show raw exception details
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Serenity.Extensions.DependencyInjection.ServiceCollectionExtensions.AddJsonTexts(ILocalTextRegistry registry, IFileProvider provider, String subpath, Boolean recursive) in C:\Sandbox\startsharp\Serenity\src\Serenity.Net.Services\RequestHandlers\Helpers\ServiceCollectionExtensions.cs:line 287
   at Serenity.Extensions.DependencyInjection.ServiceCollectionExtensions.AddBaseTexts(IServiceProvider provider, IFileProvider webFileProvider) in C:\Sandbox\startsharp\Serenity\src\Serenity.Net.Services\RequestHandlers\Helpers\ServiceCollectionExtensions.cs:line 224
   at Fascino.Startup.InitializeLocalTexts(IServiceProvider services) in D:\CitySoft.Co.Ltd\New-SOURCE_CODE\Standrad\Proj_Fascino\Fascino.Branch.Web\Initialization\Startup.cs:line 258
   at Fascino.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in D:\CitySoft.Co.Ltd\New-SOURCE_CODE\Standrad\Proj_Fascino\Fascino.Branch.Web\Initialization\Startup.cs:line 282
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
   at StackExchange.Exceptional.ExceptionalStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Fascino.Program.Main(String[] args) in D:\CitySoft.Co.Ltd\New-SOURCE_CODE\Standrad\Proj_Fascino\Fascino.Branch.Web\Initialization\Program.cs:line 11
.NET 6.0.20 X64 v6.0.0.0    |   Microsoft.AspNetCore.Hosting version 6.0.20+39e0501ee91dcf2b9b885d647795184815fb0408    |    Microsoft Windows 10.0.19045    |   Need help?

### What did you expect to happen?

-

### How to reproduce?

-

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

Serenity.Scripts 6.5.1

**Comment by VictorTomaili** [comment]
Check your local texts files and use discussions instead of issues to get help.
