### ISSUE TITLE
Autherization error

### ISSUE THREAD

**Issue by MohamedEbrahimSaad** [serenity-is/Serenity#7028]
### Before submitting the bug report, please read and check the following items

- [X] This isn't a feature request or a discussion topic (Please use discussions for that)
- [X] I have searched open and closed issues for duplicates
- [X] I have searched the documentation on the Serenity Platform website https://serenity.is/docs/
- [X] I have read the frequently asked questions https://serenity.is/docs/startsharp/faq
- [X] I have searched my problem in the discussions and the old issues https://github.com/serenity-is/Serenity/discussions

### What happened?

Description:

I am writing to report two critical issues encountered while working on a new Serenity Core project. These issues affect the creation of new users with specific permissions and a code error related to the ExtensionsTexts namespace in the project.

Issue 1: User Creation Error

When creating a new user in the Serenity Core project and assigning only one permission or some permissions to the user, the following error is encountered:

Microsoft.Data.SqlClient.SqlException (0x80131904): The multi-part identifier "jRole.RoleName" could not be bound. 
at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

This error seems to be tied to the scenario where a user is given only one permission or given not all permissions. The error does not occur when the user is assigned all permissions.

Issue 2: Code Error in _Sidebar.cshtml

When creating a new project, the code snippet below results in an error in the _Sidebar.cshtml file:

 
@ExtensionsTexts.Forms.Membership.ChangePassword.FormTitle.ToString(Localizer)
The error message received is:
 
The name 'ExtensionsTexts' does not exist in the current context.

This suggests that there may be an issue with the namespace or context in which ExtensionsTexts is being referenced.

Steps to Reproduce:

Issue 1:

Create a new Serenity Core project.
Create a new user and assign only one permission.
Observe the mentioned SQL exception.

Issue 2:

Create a new Serenity Core project.
Include the provided code snippet in the _Sidebar.cshtml file.
Observe the error related to the ExtensionsTexts namespace.
Expected Results:

Issue 1:

Users should be able to be created with any number of permissions without encountering SQL exceptions.
Issue 2:

The ExtensionsTexts namespace should be recognized in the context of the _Sidebar.cshtml file without resulting in an error.
![image](https://github.com/serenity-is/Serenity/assets/10961851/c471f98b-ea8e-4476-b10b-7fa538031580)

### What did you expect to happen?

Issue 1:

Create a new Serenity Core project.
Create a new user and assign only one permission.
Observe the mentioned SQL exception.

Issue 2:

Create a new Serenity Core project.
Include the provided code snippet in the _Sidebar.cshtml file.
Observe the error related to the ExtensionsTexts namespace.
Expected Results:

Issue 1:

Users should be able to be created with any number of permissions without encountering SQL exceptions.
Issue 2:

The ExtensionsTexts namespace should be recognized in the context of the _Sidebar.cshtml file without resulting in an error.
![image](https://github.com/serenity-is/Serenity/assets/10961851/64812374-a9cb-4ec2-80b1-711e2b47e808)

### How to reproduce?

Issue 1:

Create a new Serenity Core project.
Create a new user and assign only one permission.
Observe the mentioned SQL exception.

Issue 2:

Create a new Serenity Core project.
Include the provided code snippet in the _Sidebar.cshtml file.
Observe the error related to the ExtensionsTexts namespace.
Expected Results:

Issue 1:

Users should be able to be created with any number of permissions without encountering SQL exceptions.
Issue 2:

The ExtensionsTexts namespace should be recognized in the context of the _Sidebar.cshtml file without resulting in an error.

### What Serenity Nuget Versions are you seeing the problem on? (separated by comma)

last version

### Relevant log output

```console
Microsoft.Data.SqlClient.SqlException (0x80131904): The multi-part identifier "jRole.RoleName" could not be bound. 
at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
```

### Serene template version

.net core 6

### Additional information

please let me know when fix it

**Comment by MohamedEbrahimSaad** [comment]
![image](https://github.com/serenity-is/Serenity/assets/10961851/14f3b292-933f-4543-a610-1e02a907ec89)

**Comment by VictorTomaili** [comment]
The issue related "The multi-part identifier "jRole.RoleName" could not be bound." is fixed. There is no issue about "ExtensionsTexts" found. You may need to restore your npm package and check the version of the npm packages.

**Comment by nahidulislam-cse15** [comment]
how to solve this problem ?
@VictorTomaili
